apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    purpose: expense
    tier: db

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      project: expense
      tier: db
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: web
    spec:
      containers:
      - name: nginx
        image: joindevops/mysql:v1.0
        